name: Solana Bot
on:
  schedule:
    - cron: '*/5 * * * *' # هاد البوت غيخدم أوتوماتيكياً كل 5 دقائق
  workflow_dispatch: # باش تقدر تخدمو يدوياً وقتما بغيتي

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests solders base58 python-dotenv
      - name: Run Bot
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          HELIUS_API_KEY: ${{ secrets.HELIUS_API_KEY }}
        run: python main.py
