jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Fix DNS and Install dependencies
        run: |
          echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf
          pip install httpx solana solders base58
      - name: Run Bot
        run: python main.py
